<main class="main-content">
	<div class="container">
			<div class="page">
				<h1 class="display-4" style="margin-bottom:0px;">Cadastro Vendedor</h1>
				<div class="container pl-3 pt-3 pr-3 pb-0 bg-white rounded m-0">
				<form action="/inserir_vendedor" method="post">
					<div class="row">

						<div class="col-6 p-2">
							<div class="form-group  mb-3">
								<label for="nome"><strong>Nome</strong></label>
								<input id="nome" class="form-control col-8" type="text" name="nome">
							</div>

							<div class="form-group mb-3">
								<label for="username"><strong>Username</strong></label>
								<input id="username" class="form-control col-8" type="text" name="username">
							</div>

							<div class="form-group mb-3">
								<label for="email"><strong>E-mail</strong></label>
								<input id="email" class="form-control col-8" type="email" name="email">
							</div>

							<div class="form-group mb-3">
								<label for="senha"><strong>Senha</strong></label>
								<input id="senha" class="form-control col-8" type="password" name="senha">
							</div>



						</div>

						<div class="col-6 p-2">
							<div class="form-group  mb-3">
								<label for="cep"><strong>Cep</strong></label>
								<input id="cep" class="form-control col-8" type="text" name="cep">
							</div>

							<div class="form-group  mb-3">
								<label for="logradouro"> <strong>Logradouro</strong></label>
								<input id="logradouro" class="form-control col-8" type="text" name="logradouro">
							</div>

							<div class="form-group  mb-3">
								<label for="bairro"> <strong>Bairro</strong> </label>
								<input id="bairro" class="form-control col-8" type="text" name="bairro">
							</div>

							<div class="form-group  mb-3">
								<label for="numero"> <strong>Número</strong> </label>
								<input id="numero" class="form-control col-3" min="1" type="number" name="numero">
							</div>
						</div>

						<div class="footer col-12 m-0 p-2 bg-light justify-content-end d-flex">
							<button type="reset" class="btn btn-danger mr-2">Limpar</button>
							<button type="submit" class="btn btn-success">Cadastrar-se</button>
						</div>
					</div>
				</form>
				</div>
	    </div>
  </div>
</main>
