
<div class="col-md-4">
		<aside class="profile-nav alt">
				<section class="card">
						<div class="card-header user-header alt bg-dark">
								<div class="media">
										<a href="#">
												<img class="align-self-center rounded-circle mr-3" style="width:85px; height:85px;" alt="" src="assets/dashboard/images/admin.jpg">
										</a>
										<div class="media-body">
												<h2 class="text-light display-6"><?= $this->view->nome[0] ?></h2>
												<p>Vendedor@</p>
										</div>
								</div>
						</div>


						<ul class="list-group list-group-flush">
								<li class="list-group-item">
										<a href="/perfil"> <i class="fa fa-user"></i> Meu perfil <span class="badge badge-primary pull-right"> <i class="fa fa-pencil"></i> </span></a>
								</li>
								<li class="list-group-item">
										<a href="#"> <i class="fa fa-tasks"></i> Vendidos <span class="badge badge-danger pull-right">0</span></a>
								</li>
								<!--
								<li class="list-group-item">
										<a href="#"> <i class="fa fa-bell-o"></i> Notificação <span class="badge badge-success pull-right">0</span></a>
								</li>
								<li class="list-group-item">
										<a href="#"> <i class="fa fa-comments-o"></i> Mensagem <span class="badge badge-warning pull-right r-activity">0</span></a>
								</li>
							-->
						</ul>

				</section>
		</aside>
</div>

<div class="col-xl-3 col-lg-6">
		 <section class="card">
				 <div style="background-Color:#24be42;" class="twt-feed blue-bg">


						 <div class="media">
								 <a href="#">
										 <!--<img class="align-self-center rounded-circle mr-3" style="width:85px; height:85px;" alt="" src="assets/dashboard/images/admin.jpg">-->
								 </a>
								 <div class="media-body">
										 <h2 class="text-white display-6">Produtos</h2>
										 <p class="text-light">cadastrados</p>
								 </div>
						 </div>
				 </div>
				 <div class="weather-category twt-category">
						 <ul>
								 <a href="/cursos">	<li class="active text-success">
										 <h5>0</h5>
										 Produtos
								 </li>
								 </a>
								 <li>
									 <a  class="text-primary" href="/professores">
										 <h5>0</h5>
										 Pedidos
								 </li>
								 </a>
								 <a  href="/alunos">
								 <li class="text-success">
										 <h5>0</h5>
										 Views
								 </li>
								 </a>

						 </ul>
				 </div>

				 <footer class="twt-footer">

						 <!--conteudo-->
						 <span class="pull-right">
								 <a class="text-info" href="#">entrar</a>
						 </span>
				 </footer>
		 </section>
 </div>
