<!doctype html>
<html class="no-js" lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>MarketPlace - Jogos</title>
    <meta name="description" content="Sufee Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="apple-icon.png">
    <link rel="shortcut icon" href="favicon.ico">

    <link rel="stylesheet" href="assets/dashboard/css/normalize.css">
    <link rel="stylesheet" href="assets/dashboard/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/dashboard/css/font-awesome.min.css">
    <link rel="stylesheet" href="assets/dashboard/css/themify-icons.css">
    <link rel="stylesheet" href="assets/dashboard/css/flag-icon.min.css">
    <link rel="stylesheet" href="assets/dashboard/css/cs-skin-elastic.css">

    <link rel="stylesheet" href="assets/dashboard/scss/style.css">
    <link href="assets/dashboard/css/lib/vector-map/jqvmap.min.css" rel="stylesheet">


</head>
<body>

    <!-- Left Panel -->
    <aside id="left-panel" class="left-panel">
        <nav class="navbar navbar-expand-sm navbar-default">

            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="/vendedor">
									<img src="assets/dashboard/images/logo3.png" alt="Logo">
								</a>
                <a class="navbar-brand hidden" href="/vendedor">
									<img src="assets/dashboard/images/logo2.png" alt="Logo">
								</a>
            </div>

            <div id="main-menu" class="main-menu collapse navbar-collapse">
                <ul class="nav navbar-nav">

                    <h3 class="menu-title">Opções</h3><!-- /.menu-title -->

                    <li class="menu-item-has-children dropdown show">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="menu-icon fa fa-laptop"></i>Cadastros</a>
                        <ul class="sub-menu children dropdown-menu show">
													  <li><i class="fa fa-book"></i><a href="/cursos">Produtos</a></li>
                        </ul>
                    </li>

                </ul>
            </div><!-- /.navbar-collapse -->
        </nav>
    </aside><!-- /#left-panel -->

    <!-- Left Panel -->

    <!-- Right Panel -->

    <div id="right-panel" class="right-panel">

        <!-- Header-->
        <header id="header" class="header">

            <div class="header-menu">

                <div class="col-sm-7">
                    <a id="menuToggle--" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
                    <div class="header-left">
                        <button class="search-trigger"><i class="fa fa-search"></i></button>
                        <div class="form-inline">
                            <form class="search-form">
                                <input class="form-control mr-sm-2" type="text" placeholder="procurar ..." aria-label="Search">
                                <button class="search-close" type="submit"><i class="fa fa-close"></i></button>
                            </form>
                        </div>

                    </div>
                </div>

                <div class="col-sm-5">
                    <div class="user-area dropdown float-right">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img class="user-avatar rounded-circle" src="assets/dashboard/images/admin.jpg" alt="User Avatar">
                        </a>

                        <div class="user-menu dropdown-menu">
                                <a class="nav-link" href="/perfil"><i class="fa fa- user"></i>Meu perfil</a>

                                <a class="nav-link" href="#"><i class="fa fa- user"></i>Notificações<!-- <span class="count">13</span> --></a>

                                <a class="nav-link" href="#"><i class="fa fa -cog"></i>Configurações</a>

                                <a class="nav-link" href="/logout"><i class="fa fa-power -off"></i>Sair</a>
                        </div>
                    </div>

                </div>
            </div>

        </header><!-- /header -->
        <!-- Header-->

        <div class="breadcrumbs">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>MarketPlace</h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li class="active"><?= $_SESSION['nome'] ?></li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

        <div class="content mt-3 bg-white p-3">
					<!--AQUI ENTRA O CONTEUDO DO SITE-->

					<?=  $this->content(); ?>

        </div> <!-- .content -->
    </div><!-- /#right-panel -->

    <!-- Right Panel -->

    <script src="assets/dashboard/js/vendor/jquery-2.1.4.min.js"></script>
		<script src="assets/dashboard/js/popper.min.js"></script>
    <script src="assets/dashboard/js/plugins.js"></script>
    <script src="assets/dashboard/js/main.js"></script>

    <script src="assets/dashboard/js/lib/vector-map/jquery.vmap.js"></script>
    <script src="assets/dashboard/js/lib/vector-map/jquery.vmap.min.js"></script>
    <script src="assets/dashboard/js/lib/vector-map/jquery.vmap.sampledata.js"></script>
    <script src="assets/dashboard/js/lib/vector-map/country/jquery.vmap.world.js"></script>

</body>
</html>
