<!DOCTYPE html>
<html lang="pt-br" dir="ltr">
	<head>
		<meta charset="utf-8">
		<title>MarketPlace Jogos</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1">

		<!-- Loading third party fonts -->
		<link href="http://fonts.googleapis.com/css?family=Roboto:100,300,400,700|" rel="stylesheet" type="text/css">
		<link href="assets/eccomerce/fonts/font-awesome.min.css" rel="stylesheet" type="text/css">
		<link href="assets/eccomerce/fonts/lineo-icon/style.css" rel="stylesheet" type="text/css">
		<link rel="stylesheet" href="assets/eccomerce/bootstrap.css">
		<!-- Loading main css file -->
		<link rel="stylesheet" href="assets/eccomerce/style.css">
	</head>
	<body class="slider-collapse">

		<div id="site-content">
			<div class="site-header">
				<div class="container">
					<a href="/" id="branding">
						<img src="assets/eccomerce/images/logo.png" alt="" class="logo">
						<div class="logo-text">
							<h1 class="site-title">Hypersinc</h1>
							<small class="site-description">Os melhores jogos</small>
						</div>
					</a> <!-- #branding -->

					<div class="right-section pull-right">
					<!--	<a href="cart.html" class="cart"><i class="icon-cart"></i> 0 items in cart</a>-->
						<a href="#" class="login-button">Login/Registrar-se</a>
					</div> <!-- .right-section -->

					<div class="main-navigation">
						<button class="toggle-menu"><i class="fa fa-bars"></i></button>
						<ul class="menu">
							<li class="menu-item home current-menu-item"><a href="/"><i class="icon-home"></i></a></li>
							<li class="menu-item"><a href="products.html">Accessories</a></li>
							<li class="menu-item"><a href="products.html">Promotions</a></li>
							<li class="menu-item"><a href="products.html">PC</a></li>
							<li class="menu-item"><a href="products.html">Playstation</a></li>
							<li class="menu-item"><a href="products.html">Xbox</a></li>
							<li class="menu-item"><a href="products.html">Wii</a></li>
						</ul> <!-- .menu -->
						<div class="search-form">
							<label><img src="assets/eccomerce/images/icon-search.png"></label>
							<input type="text" placeholder="Procurar...">
						</div> <!-- .search-form -->

						<div class="mobile-navigation"></div> <!-- .mobile-navigation -->
					</div> <!-- .main-navigation -->
				</div> <!-- .container -->
			</div> <!-- .site-header -->

			<?= $this->content() ?>



			<div class="site-footer">
				<div class="container">
					<div class="row">
						<div class="col-md-2">
							<div class="widget">
								<h3 class="widget-title">Information</h3>
								<ul class="no-bullet">
									<li><a href="#">Site map</a></li>
									<li><a href="#">About us</a></li>
									<li><a href="#">FAQ</a></li>
									<li><a href="#">Privacy Policy</a></li>
									<li><a href="#">Contact</a></li>
								</ul>
							</div> <!-- .widget -->
						</div> <!-- column -->
						<div class="col-md-2">
							<div class="widget">
								<h3 class="widget-title">Consumer Service</h3>
								<ul class="no-bullet">
									<li><a href="#">Secure</a></li>
									<li><a href="#">Shipping &amp; Returns</a></li>
									<li><a href="#">Shipping</a></li>
									<li><a href="#">Orders &amp; Returns</a></li>
									<li><a href="#">Group Sales</a></li>
								</ul>
							</div> <!-- .widget -->
						</div> <!-- column -->
						<div class="col-md-2">
							<div class="widget">
								<h3 class="widget-title">My Account</h3>
								<ul class="no-bullet">
									<li><a href="#">Login/Register</a></li>
									<li><a href="#">Settings</a></li>
									<li><a href="#">Cart</a></li>
									<li><a href="#">Order Tracking</a></li>
									<li><a href="#">Logout</a></li>
								</ul>
							</div> <!-- .widget -->
						</div> <!-- column -->
						<div class="col-md-6">
							<div class="widget">
								<h3 class="widget-title">Join our newsletter</h3>
								<form action="#" class="newsletter-form">
									<input type="text" placeholder="Enter your email...">
									<input type="submit" value="Subsribe">
								</form>
							</div> <!-- .widget -->
						</div> <!-- column -->
					</div><!-- .row -->

					<div class="colophon">
						<div class="copy">Copyright <?= date('Y') ?> Hypersinc. Desenvolvido por um Bahiano.</div>
						<div class="social-links square">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-google-plus"></i></a>
							<a href="#"><i class="fa fa-pinterest"></i></a>
						</div> <!-- .social-links -->
					</div> <!-- .colophon -->
				</div> <!-- .container -->
			</div> <!-- .site-footer -->
		</div>

		<div class="overlay"></div>


		<div class="auth-popup popup">
			<a href="#" class="close"><i class="fa fa-times"></i></a>
			<div class="row">
				<div class="col-md-6">
					<h2 class="section-title">Login</h2>
					<form action="/validar" method="post">
						<input type="email" placeholder="Email..." name="email">
						<input type="password" placeholder="Senha..." name="senha">
						<select id="select" class="form-control" name="tipo">
							<option value="cliente">Cliente</option>
							<option value="vendedor">Vendedor</option>
						</select><br>
						<input type="submit" value="Entrar">
					</form>
				</div> <!-- .column -->
				<div class="col-md-6">
					<h2 class="section-title">Criar uma conta</h2>
					<form action="#">
						<input type="text" placeholder="Nome...">
						<input type="text" placeholder="Email...">
						<input type="password" placeholder="Senha..."><br>
						<small><a id="lin" href="/cadastro_vendedor">Quero ser um vendedor</a></small>
						<input type="submit" value="Registrar-se">
					</form>
				</div> <!-- .column -->
			</div> <!-- .row -->
		</div> <!-- .auth-popup -->



		<script src="assets/eccomerce/js/jquery-1.11.1.min.js"></script>
		<script src="assets/eccomerce/js/plugins.js"></script>
		<script src="assets/eccomerce/js/app.js"></script>
	</body>
</html>
